# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   format_chain( name )
#
#Given an chain name, generates the partial iptables rule to faciliate appending
#a rule to given chain.
#
#Examples:
#
#  # returns '-A INPUT'
#  format_chain('INPUT')
#
#  # returns '-A LOGNDUMP'
#  format_chain('LOGNDUMP')
#
#  # throws ParseError
#  format_chain('SOME CHAIN')
#
#
Puppet::Functions.create_function(:'iptables::format_chain') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    chain = 'INPUT'
    chain = args[0] unless args[0] == nil

    if chain == :undef or chain == ''
      raise Puppet::ParseError, \
        "chain name cannot be empty"
    end

    # Do some validation here
    if chain =~ /\s/
      raise Puppet::ParseError, \
        "chain name cannot contain whitespace - \"#{chain}\""
    end

    return "-A #{chain}"
  
  end
end
